const dummyProducts = [
  {
    id: 1,
    name: REMOVED_SECRETClassic T-ShirtREMOVED_SECRET,
    category: REMOVED_SECRETClothesREMOVED_SECRET,
    price: 19.99,
    image: REMOVED_SECRET/images/products/clothes-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETComfortable cotton t-shirt with classic fit.REMOVED_SECRET,
    comments: [REMOVED_SECRETNice quality!REMOVED_SECRET, REMOVED_SECRETVery comfy.REMOVED_SECRET, REMOVED_SECRETGood value.REMOVED_SECRET],
    rating: 4.5,
  },
  {
    id: 2,
    name: REMOVED_SECRETBlue Denim JacketREMOVED_SECRET,
    category: REMOVED_SECRETClothesREMOVED_SECRET,
    price: 49.99,
    image: REMOVED_SECRET/images/products/clothes-2.jpgREMOVED_SECRET,
    description: REMOVED_SECRETStylish blue denim jacket for all seasons.REMOVED_SECRET,
    comments: [REMOVED_SECRETCool design!REMOVED_SECRET, REMOVED_SECRETMy favorite jacket.REMOVED_SECRET, REMOVED_SECRETHighly recommend.REMOVED_SECRET],
    rating: 4.8,
  },
  {
    id: 3,
    name: REMOVED_SECRETSporty SneakersREMOVED_SECRET,
    category: REMOVED_SECRETFootwearREMOVED_SECRET,
    price: 69.99,
    image: REMOVED_SECRET/images/products/shoe-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETLightweight sneakers perfect for daily wear.REMOVED_SECRET,
    comments: [REMOVED_SECRETGood for running.REMOVED_SECRET, REMOVED_SECRETLove the style.REMOVED_SECRET],
    rating: 4.3,
  },
  {
    id: 4,
    name: REMOVED_SECRETLeather HandbagREMOVED_SECRET,
    category: REMOVED_SECRETAccessoriesREMOVED_SECRET,
    price: 89.99,
    image: REMOVED_SECRET/images/products/sport-5.jpgREMOVED_SECRET,
    description: REMOVED_SECRETElegant leather handbag with spacious interior.REMOVED_SECRET,
    comments: [REMOVED_SECRETBeautiful bag!REMOVED_SECRET, REMOVED_SECRETVery practical.REMOVED_SECRET],
    rating: 4.7,
  },
  {
    id: 5,
    name: REMOVED_SECRETWinter ScarfREMOVED_SECRET,
    category: REMOVED_SECRETAccessoriesREMOVED_SECRET,
    price: 14.99,
    image: REMOVED_SECRET/images/products/clothes-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETWarm and cozy scarf for cold days.REMOVED_SECRET,
    comments: [REMOVED_SECRETSuper warm!REMOVED_SECRET, REMOVED_SECRETNice color.REMOVED_SECRET],
    rating: 4.4,
  },
  {
    id: 6,
    name: REMOVED_SECRETWinter ScarfREMOVED_SECRET,
    category: REMOVED_SECRETAccessoriesREMOVED_SECRET,
    price: 14.99,
    image: REMOVED_SECRET/images/products/clothes-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETWarm and cozy scarf for cold days.REMOVED_SECRET,
    comments: [REMOVED_SECRETSuper warm!REMOVED_SECRET, REMOVED_SECRETNice color.REMOVED_SECRET],
    rating: 4.4,
  },
  {
    id: 7,
    name: REMOVED_SECRETWinter ScarfREMOVED_SECRET,
    category: REMOVED_SECRETAccessoriesREMOVED_SECRET,
    price: 14.99,
    image: REMOVED_SECRET/images/products/clothes-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETWarm and cozy scarf for cold days.REMOVED_SECRET,
    comments: [REMOVED_SECRETSuper warm!REMOVED_SECRET, REMOVED_SECRETNice color.REMOVED_SECRET],
    rating: 4.4,
  },
  {
    id: 8,
    name: REMOVED_SECRETWinter ScarfREMOVED_SECRET,
    category: REMOVED_SECRETAccessoriesREMOVED_SECRET,
    price: 14.99,
    image: REMOVED_SECRET/images/products/clothes-1.jpgREMOVED_SECRET,
    description: REMOVED_SECRETWarm and cozy scarf for cold days.REMOVED_SECRET,
    comments: [REMOVED_SECRETSuper warm!REMOVED_SECRET, REMOVED_SECRETNice color.REMOVED_SECRET],
    rating: 4.4,
  },
];

export default dummyProducts;
