const dummyProducts = [
  {
    id: 1,
    name: "Classic T-Shirt",
    category: "Clothes",
    price: 19.99,
    image: "/images/products/clothes-1.jpg",
    description: "Comfortable cotton t-shirt with classic fit.",
    comments: ["Nice quality!", "Very comfy.", "Good value."],
    rating: 4.5,
  },
  {
    id: 2,
    name: "Blue Denim Jacket",
    category: "Clothes",
    price: 49.99,
    image: "/images/products/clothes-2.jpg",
    description: "Stylish blue denim jacket for all seasons.",
    comments: ["Cool design!", "My favorite jacket.", "Highly recommend."],
    rating: 4.8,
  },
  {
    id: 3,
    name: "Sporty Sneakers",
    category: "Footwear",
    price: 69.99,
    image: "/images/products/shoe-1.jpg",
    description: "Lightweight sneakers perfect for daily wear.",
    comments: ["Good for running.", "Love the style."],
    rating: 4.3,
  },
  {
    id: 4,
    name: "Leather Handbag",
    category: "Accessories",
    price: 89.99,
    image: "/images/products/sport-5.jpg",
    description: "Elegant leather handbag with spacious interior.",
    comments: ["Beautiful bag!", "Very practical."],
    rating: 4.7,
  },
  {
    id: 5,
    name: "Winter Scarf",
    category: "Accessories",
    price: 14.99,
    image: "/images/products/clothes-1.jpg",
    description: "Warm and cozy scarf for cold days.",
    comments: ["Super warm!", "Nice color."],
    rating: 4.4,
  },
  {
    id: 6,
    name: "Winter Scarf",
    category: "Accessories",
    price: 14.99,
    image: "/images/products/clothes-1.jpg",
    description: "Warm and cozy scarf for cold days.",
    comments: ["Super warm!", "Nice color."],
    rating: 4.4,
  },
  {
    id: 7,
    name: "Winter Scarf",
    category: "Accessories",
    price: 14.99,
    image: "/images/products/clothes-1.jpg",
    description: "Warm and cozy scarf for cold days.",
    comments: ["Super warm!", "Nice color."],
    rating: 4.4,
  },
  {
    id: 8,
    name: "Winter Scarf",
    category: "Accessories",
    price: 14.99,
    image: "/images/products/clothes-1.jpg",
    description: "Warm and cozy scarf for cold days.",
    comments: ["Super warm!", "Nice color."],
    rating: 4.4,
  },
];

export default dummyProducts;
